[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TP_Programmation-Fonctionnelle"
authors = [{name = "Bubuclem"}]
dynamic = ["version", "description"]